name: lingo_master
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  excel: ^2.1.0
  path_provider: ^2.0.11
  flutter_tts: ^4.2.2
  audioplayers: ^5.2.0
  fluro: ^2.0.5
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  provider: ^6.1.4
  equatable: ^2.0.7
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  free_dictionary_api_v2: ^1.0.3
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  yaml: ^3.1.0
  mime: ^1.0.0
  http_parser: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/course/
    - assets/configs/api-config.yaml   # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

